export const nameMap = new Map(
    [Function, "Function" ],
    [Function.prototype, "Function.prototyp" ],
    [Object, "Object" ],
    [Object.prototype, "Object.prototyp" ],
    [Boolean, "Boolean" ],
    [Boolean.prototype, "Boolean.prototyp" ],
    [Number, "Number" ],
    [Number.prototype, "Number.prototyp" ],
    [String, "String" ],
    [String.prototype, "String.prototyp" ],
    [Array, "Array" ],
    [Array.prototype, "Array.prototyp" ],
    [RegExp, "RegExp" ],
    [RegExp.prototype, "RegExp.prototyp" ],
    [Symbol, "Symbol" ],
    [Symbol.prototype, "Symbol.prototyp" ],
    [Error, "Error" ],
    [Error.prototype, "Error.prototyp" ],
    [Promise, "Promise" ],
    [Promise.prototype, "Promise.prototyp" ],
)
export default new Map(
    [Function, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Function",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Function.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
    }],
    [Function.prototype, {
        "length": {
            "value": 0,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "arguments": {
            "get": Object.getOwnPropertyDescriptor(Function.prototype, "arguments").get,
            "set": Object.getOwnPropertyDescriptor(Function.prototype, "arguments").set, 
            "enumerable": false,
            "configurable": true,
        },
        "caller": {
            "get": Object.getOwnPropertyDescriptor(Function.prototype, "caller").get,
            "set": Object.getOwnPropertyDescriptor(Function.prototype, "caller").get,
            "enumerable": false,
            "configurable": true,
        },
        "constructor": {
            "value": Function,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "apply": {
            "value": Function.prototype.apply /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "bind": {
            "value": Function.prototype.bind /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "call": {
            "value": Function.prototype.call /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Function.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Object, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Object",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Object.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "assign": {
            "value": Object.assign /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "getOwnPropertyDescriptor": {
            "value": Object.getOwnPropertyDescriptor /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "getOwnPropertyDescriptors": {
            "value": Object.getOwnPropertyDescriptors /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "getOwnPropertyNames": {
            "value": Object.getOwnPropertyNames /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "getOwnPropertySymbols": {
            "value": Object.getOwnPropertySymbols /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "hasOwn": {
            "value": Object.hasOwn /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "is": {
            "value": Object.is /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "preventExtensions": {
            "value": Object.preventExtensions /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "seal": {
            "value": Object.seal /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "create": {
            "value": Object.create /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "defineProperties": {
            "value": Object.defineProperties /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "defineProperty": {
            "value": Object.defineProperty /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "freeze": {
            "value": Object.freeze /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "getPrototypeOf": {
            "value": Object.getPrototypeOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "setPrototypeOf": {
            "value": Object.setPrototypeOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isExtensible": {
            "value": Object.isExtensible /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isFrozen": {
            "value": Object.isFrozen /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isSealed": {
            "value": Object.isSealed /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "keys": {
            "value": Object.keys /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "entries": {
            "value": Object.entries /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fromEntries": {
            "value": Object.fromEntries /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "values": {
            "value": Object.values /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "groupBy": {
            "value": Object.groupBy /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Object.prototype, {
        "constructor": {
            "value": Object,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "__defineGetter__": {
            "value": globalThis["__defineGetter__"],
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "__defineSetter__": {
            "value": globalThis["__defineSetter__"],
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "hasOwnProperty": {
            "value": Object.prototype.hasOwnProperty,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "__lookupGetter__": {
            "value": globalThis["__lookupGetter__"],
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "__lookupSetter__": {
            "value": globalThis["__lookupSetter__"],
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isPrototypeOf": {
            "value": Object.prototype.isPrototypeOf,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "propertyIsEnumerable": {
            "value": Object.prototype.propertyIsEnumerable,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Object.prototype.toString,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "valueOf": {
            "value": Object.prototype.valueOf,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toLocaleString": {
            "value": Object.prototype.toLocaleString,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Boolean, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Boolean",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Boolean.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
    }],
    [Boolean.prototype, {
        "constructor": {
            "value": Boolean,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Boolean.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "valueOf": {
            "value": Boolean.prototype.valueOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Number, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Number",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Number.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "isFinite": {
            "value": Number.isFinite /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isInteger": {
            "value": Number.isInteger /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isNaN": {
            "value": Number.isNaN /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isSafeInteger": {
            "value": Number.isSafeInteger /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "parseFloat": {
            "value": Number.parseFloat,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "parseInt": {
            "value": Number.parseInt,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "MAX_VALUE": {
            "value": 1.7976931348623157e+308,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "MIN_VALUE": {
            "value": 5e-324,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "NaN": {
            "value": NaN,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "NEGATIVE_INFINITY": {
            "value": -Infinity,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "POSITIVE_INFINITY": {
            "value": Infinity,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "MAX_SAFE_INTEGER": {
            "value": 9007199254740991,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "MIN_SAFE_INTEGER": {
            "value": -9007199254740991,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "EPSILON": {
            "value": 2.220446049250313e-16,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
    }],
    [Number.prototype, {
        "constructor": {
            "value": Number,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toExponential": {
            "value": Number.prototype.toExponential /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toFixed": {
            "value": Number.prototype.toFixed /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toPrecision": {
            "value": Number.prototype.toPrecision /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Number.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "valueOf": {
            "value": Number.prototype.valueOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toLocaleString": {
            "value": Number.prototype.toLocaleString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [String, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "String",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": String.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "fromCharCode": {
            "value": String.fromCharCode /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fromCodePoint": {
            "value": String.fromCodePoint /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "raw": {
            "value": String.raw /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [String.prototype, {
        "length": {
            "value": 0,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "constructor": {
            "value": String,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "anchor": {
            "value": String.prototype.anchor /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "at": {
            "value": String.prototype.at /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "big": {
            "value": String.prototype.big /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "blink": {
            "value": String.prototype.blink /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "bold": {
            "value": String.prototype.bold /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "charAt": {
            "value": String.prototype.charAt /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "charCodeAt": {
            "value": String.prototype.charCodeAt /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "codePointAt": {
            "value": String.prototype.codePointAt /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "concat": {
            "value": String.prototype.concat /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "endsWith": {
            "value": String.prototype.endsWith /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fontcolor": {
            "value": String.prototype.fontcolor /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fontsize": {
            "value": String.prototype.fontsize /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fixed": {
            "value": String.prototype.fixed /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "includes": {
            "value": String.prototype.includes /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "indexOf": {
            "value": String.prototype.indexOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "isWellFormed": {
            "value": String.prototype.isWellFormed /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "italics": {
            "value": String.prototype.italics /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "lastIndexOf": {
            "value": String.prototype.lastIndexOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "link": {
            "value": String.prototype.link /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "localeCompare": {
            "value": String.prototype.localeCompare /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "match": {
            "value": String.prototype.match /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "matchAll": {
            "value": String.prototype.matchAll /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "normalize": {
            "value": String.prototype.normalize /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "padEnd": {
            "value": String.prototype.padEnd /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "padStart": {
            "value": String.prototype.padStart /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "repeat": {
            "value": String.prototype.repeat /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "replace": {
            "value": String.prototype.replace /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "replaceAll": {
            "value": String.prototype.replaceAll /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "search": {
            "value": String.prototype.search /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "slice": {
            "value": String.prototype.slice /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "small": {
            "value": String.prototype.small /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "split": {
            "value": String.prototype.split /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "strike": {
            "value": String.prototype.strike /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "sub": {
            "value": String.prototype.sub /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "substr": {
            "value": String.prototype.substr /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "substring": {
            "value": String.prototype.substring /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "sup": {
            "value": String.prototype.sup /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "startsWith": {
            "value": String.prototype.startsWith /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": String.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toWellFormed": {
            "value": String.prototype.toWellFormed /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "trim": {
            "value": String.prototype.trim /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "trimStart": {
            "value": String.prototype.trimStart /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "trimLeft": {
            "value": String.prototype.trimStart /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "trimEnd": {
            "value": String.prototype.trimEnd /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "trimRight": {
            "value": String.prototype.trimEnd /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toLocaleLowerCase": {
            "value": String.prototype.toLocaleLowerCase /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toLocaleUpperCase": {
            "value": String.prototype.toLocaleUpperCase /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toLowerCase": {
            "value": String.prototype.toLowerCase /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toUpperCase": {
            "value": String.prototype.toUpperCase /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "valueOf": {
            "value": String.prototype.valueOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Array, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Array",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Array.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "isArray": {
            "value": Array.isArray /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "from": {
            "value": Array.from /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fromAsync": {
            "value": Array.fromAsync /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "of": {
            "value": Array.of /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Array.prototype, {
        "length": {
            "value": 0,
            "writable": true,
            "enumerable": false,
            "configurable": false,
        },
        "constructor": {
            "value": Array,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "at": {
            "value": Array.prototype.at /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "concat": {
            "value": Array.prototype.concat /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "copyWithin": {
            "value": Array.prototype.copyWithin /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "fill": {
            "value": Array.prototype.fill /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "find": {
            "value": Array.prototype.find /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "findIndex": {
            "value": Array.prototype.findIndex /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "findLast": {
            "value": Array.prototype.findLast /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "findLastIndex": {
            "value": Array.prototype.findLastIndex /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "lastIndexOf": {
            "value": Array.prototype.lastIndexOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "pop": {
            "value": Array.prototype.pop /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "push": {
            "value": Array.prototype.push /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "reverse": {
            "value": Array.prototype.reverse /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "shift": {
            "value": Array.prototype.shift /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "unshift": {
            "value": Array.prototype.unshift /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "slice": {
            "value": Array.prototype.slice /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "sort": {
            "value": Array.prototype.sort /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "splice": {
            "value": Array.prototype.splice /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "includes": {
            "value": Array.prototype.includes /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "indexOf": {
            "value": Array.prototype.indexOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "join": {
            "value": Array.prototype.join /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "keys": {
            "value": Array.prototype.keys /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "entries": {
            "value": Array.prototype.entries /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "values": {
            "value": Array.prototype.values /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "forEach": {
            "value": Array.prototype.forEach /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "filter": {
            "value": Array.prototype.filter /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "flat": {
            "value": Array.prototype.flat /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "flatMap": {
            "value": Array.prototype.flatMap /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "map": {
            "value": Array.prototype.map /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "every": {
            "value": Array.prototype.every /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "some": {
            "value": Array.prototype.some /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "reduce": {
            "value": Array.prototype.reduce /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "reduceRight": {
            "value": Array.prototype.reduceRight /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toReversed": {
            "value": Array.prototype.toReversed /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toSorted": {
            "value": Array.prototype.toSorted /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toSpliced": {
            "value": Array.prototype.toSpliced /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "with": {
            "value": Array.prototype.with /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toLocaleString": {
            "value": Array.prototype.toLocaleString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Array.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [RegExp, {
        "length": {
            "value": 2,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "RegExp",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": RegExp.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "input": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "input").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "input").set,
            "enumerable": false,
            "configurable": true,
        },
        "$_": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "$_").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "$_").set,
            "enumerable": false,
            "configurable": true,
        },
        "lastMatch": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "lastMatch").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "lastMatch").set,
            "enumerable": false,
            "configurable": true,
        },
        "$&": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "$&").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "$&").set,
            "enumerable": false,
            "configurable": true,
        },
        "lastParen": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "lastParen").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "lastParen").set,
            "enumerable": false,
            "configurable": true,
        },
        "$+": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "$+").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "$+").set,
            "enumerable": false,
            "configurable": true,
        },
        "leftContext": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "leftContext").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "leftContext").set,
            "enumerable": false,
            "configurable": true,
        },
        "$`": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "$`").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "$`").set,
            "enumerable": false,
            "configurable": true,
        },
        "rightContext": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "rightContext").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "rightContext").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$'": {
            "get": Object.getOwnPropertyDescriptor(RegExp, "$'").get,
            "set": Object.getOwnPropertyDescriptor(RegExp, "$'").set,
            "enumerable": false,
            "configurable": true,
        },
        "$1": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$1").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$1").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$2": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$2").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$2").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$3": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$3").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$3").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$4": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$4").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$4").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$5": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$5").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$5").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$6": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$6").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$6").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$7": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$7").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$7").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$8": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$8").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$8").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
        "$9": {
            "get": get Object.getOwnPropertyDescriptor(RegExp, "$9").get /*native function*/,
            "set": get Object.getOwnPropertyDescriptor(RegExp, "$9").set /*native function*/,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [RegExp.prototype, {
        "constructor": {
            "value": RegExp,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "exec": {
            "value": RegExp.prototype.exec,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "dotAll": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "dotAll").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "flags": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "flags").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "global": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "global").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "hasIndices": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "hasIndices").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "ignoreCase": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "ignoreCase").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "multiline": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "multiline").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "source": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "source").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "sticky": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "sticky").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "unicode": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "unicode").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "unicodeSets": {
            "get": Object.getOwnPropertyDescriptor(RegExp.prototype, "unicodeSets").get /*native function*/,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
        "compile": {
            "value": RegExp.prototype.compile /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": RegExp.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "test": {
            "value": RegExp.prototype.test /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Symbol, {
        "length": {
            "value": 0,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Symbol",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Symbol.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "for": {
            "value": Symbol.for /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "keyFor": {
            "value": Symbol.keyFor /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "asyncIterator": {
            "value": Symbol.asyncIterator,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "hasInstance": {
            "value": Symbol.hasInstance,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "isConcatSpreadable": {
            "value": Symbol.isConcatSpreadable,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "iterator": {
            "value": Symbol.iterator,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "match": {
            "value": Symbol.match,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "matchAll": {
            "value": Symbol.matchAll,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "replace": {
            "value": Symbol.replace,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "search": {
            "value": Symbol.search,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "species": {
            "value": Symbol.species,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "split": {
            "value": Symbol.split,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "toPrimitive": {
            "value": Symbol.toPrimitive,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "toStringTag": {
            "value": Symbol.toStringTag,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "unscopables": {
            "value": Symbol.unscopables,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "dispose": {
            "value": Symbol.dispose,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "asyncDispose": {
            "value": Symbol.asyncDispose,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "metadata": {
            "value": Symbol.metadata,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
    }],
    [Symbol.prototype, {
        "constructor": {
            "value": Symbol,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Symbol.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "valueOf": {
            "value": Symbol.prototype.valueOf /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "description": {
            "get": Object.getOwnPropertyDescriptor(Symbol.prototype, "description").get,
            "set": undefined,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Error, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Error",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Error.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "captureStackTrace": {
            "value": Error.captureStackTrace /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "stackTraceLimit": {
            "value": 10,
            "writable": true,
            "enumerable": true,
            "configurable": true,
        },
    }],
    [Error.prototype, {
        "constructor": {
            "value": Error,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Error",
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "message": {
            "value": "",
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "toString": {
            "value": Error.prototype.toString /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Promise, {
        "length": {
            "value": 1,
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "name": {
            "value": "Promise",
            "writable": false,
            "enumerable": false,
            "configurable": true,
        },
        "prototype": {
            "value": Promise.prototype,
            "writable": false,
            "enumerable": false,
            "configurable": false,
        },
        "all": {
            "value": Promise.all /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "allSettled": {
            "value": Promise.allSettled /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "any": {
            "value": Promise.any /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "race": {
            "value": Promise.race /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "resolve": {
            "value": Promise.resolve /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "reject": {
            "value": Promise.reject /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "withResolvers": {
            "value": Promise.withResolvers /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "try": {
            "value": Promise.try /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
    [Promise.prototype, {
        "constructor": {
            "value": Promise,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "then": {
            "value": Promise.prototype.then /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "catch": {
            "value": Promise.prototype.catch /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
        "finally": {
            "value": Promise.prototype.finally /*native function*/,
            "writable": true,
            "enumerable": false,
            "configurable": true,
        },
    }],
)
